// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodRestarter) DeepCopyInto(out *PodRestarter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodRestarter.
func (in *PodRestarter) DeepCopy() *PodRestarter {
	if in == nil {
		return nil
	}
	out := new(PodRestarter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodRestarter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodRestarterCriteria) DeepCopyInto(out *PodRestarterCriteria) {
	*out = *in
	if in.MaxAge != nil {
		in, out := &in.MaxAge, &out.MaxAge
		*out = new(v1.Duration)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodRestarterCriteria.
func (in *PodRestarterCriteria) DeepCopy() *PodRestarterCriteria {
	if in == nil {
		return nil
	}
	out := new(PodRestarterCriteria)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodRestarterList) DeepCopyInto(out *PodRestarterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PodRestarter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodRestarterList.
func (in *PodRestarterList) DeepCopy() *PodRestarterList {
	if in == nil {
		return nil
	}
	out := new(PodRestarterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodRestarterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodRestarterSpec) DeepCopyInto(out *PodRestarterSpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	out.CooldownPeriod = in.CooldownPeriod
	in.RestartCriteria.DeepCopyInto(&out.RestartCriteria)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodRestarterSpec.
func (in *PodRestarterSpec) DeepCopy() *PodRestarterSpec {
	if in == nil {
		return nil
	}
	out := new(PodRestarterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodRestarterStatus) DeepCopyInto(out *PodRestarterStatus) {
	*out = *in
	in.LastAction.DeepCopyInto(&out.LastAction)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodRestarterStatus.
func (in *PodRestarterStatus) DeepCopy() *PodRestarterStatus {
	if in == nil {
		return nil
	}
	out := new(PodRestarterStatus)
	in.DeepCopyInto(out)
	return out
}
