# permissions for end users to view podrestarters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podrestarter-viewer-role
rules:
- apiGroups:
  - lifecycle.rebuy.com
  resources:
  - podrestarters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lifecycle.rebuy.com
  resources:
  - podrestarters/status
  verbs:
  - get
