kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kubernetes-pod-restarter
rules:
- apiGroups:
  - lifecycle.rebuy.com
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - "*"

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-kubernetes-pod-restarter
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: kubernetes-pod-restarter
  apiGroup: rbac.authorization.k8s.io
